### ISSUE TITLE
Error during unmarshal_object for x-nullable=true property

### ISSUE THREAD

**Issue by zroadhouse-rmn** [Yelp/bravado-core#108]
I believe unmarshal_object code path is missing support for x-nullable. I get the following traceback when unmarshaling a property which a specification like:

~~~
definitions:
  SomeType:
    properties:
      extra_data:
        type: object
        x-nullable: true
~~~

Here's the stack trace:

~~~
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado/http_future.py", line 77, in result
    self.response_callbacks)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado/http_future.py", line 115, in unmarshal_response
    operation)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/response.py", line 110, in unmarshal_response
    op.swagger_spec, content_spec, content_value)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 52, in unmarshal_schema_object
    return unmarshal_object(swagger_spec, schema_object_spec, value)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 124, in unmarshal_object
    result[k] = unmarshal_schema_object(swagger_spec, prop_spec, v)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 42, in unmarshal_schema_object
    return unmarshal_array(swagger_spec, schema_object_spec, value)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 100, in unmarshal_array
    for item in array_value
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 52, in unmarshal_schema_object
    return unmarshal_object(swagger_spec, schema_object_spec, value)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 124, in unmarshal_object
    result[k] = unmarshal_schema_object(swagger_spec, prop_spec, v)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 52, in unmarshal_schema_object
    return unmarshal_object(swagger_spec, schema_object_spec, value)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 124, in unmarshal_object
    result[k] = unmarshal_schema_object(swagger_spec, prop_spec, v)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 52, in unmarshal_schema_object
    return unmarshal_object(swagger_spec, schema_object_spec, value)
  File "/Users/zroadhouse/.virtualenvs/dartclient-bravado/lib/python2.7/site-packages/bravado_core/unmarshal.py", line 117, in unmarshal_object
    type(object_value), object_value))
bravado_core.exception.SwaggerMappingError: Expected dict like type for <type 'NoneType'>:None
~~~

Discussed here:

- https://github.com/Yelp/bravado/issues/172

I'm working on a PR containing a fix.

**Comment by zroadhouse-rmn** [comment]
@sjaensch - Here's the ticket and PR.

**Comment by zroadhouse-rmn** [comment]
Actually, marshalling is also broken. Found while writing more test cases:

~~~
Traceback (most recent call last):
  File "/Users/zroadhouse/Library/Application Support/IntelliJIdea2016.1/python/helpers/pydev/pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/zroadhouse/Library/Application Support/IntelliJIdea2016.1/python/helpers/pydev/pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/zroadhouse/projects/xavier/xavier/workflow.py", line 86, in <module>
    define_datastore_xavier_emr_cluster)
  File "/Users/zroadhouse/projects/dartclient/dartclient/__init__.py", line 180, in sync_datastore
    response = self.datastore_api.createDatastore(datastore=datastore)
  File "/Users/zroadhouse/.virtualenvs/xavier/lib/python2.7/site-packages/bravado/client.py", line 250, in __call__
    self.operation, request_options, **op_kwargs)
  File "/Users/zroadhouse/.virtualenvs/xavier/lib/python2.7/site-packages/bravado/client.py", line 291, in construct_request
    construct_params(operation, request, op_kwargs)
  File "/Users/zroadhouse/.virtualenvs/xavier/lib/python2.7/site-packages/bravado/client.py", line 313, in construct_params
    marshal_param(param, param_value, request)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/param.py", line 119, in marshal_param
    value = marshal_schema_object(swagger_spec, param_spec, value)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/marshal.py", line 47, in marshal_schema_object
    return marshal_model(swagger_spec, schema_object_spec, value)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/marshal.py", line 174, in marshal_model
    return marshal_object(swagger_spec, model_spec, object_value)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/marshal.py", line 138, in marshal_object
    result[k] = marshal_schema_object(swagger_spec, prop_spec, v)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/marshal.py", line 47, in marshal_schema_object
    return marshal_model(swagger_spec, schema_object_spec, value)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/marshal.py", line 174, in marshal_model
    return marshal_object(swagger_spec, model_spec, object_value)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/marshal.py", line 138, in marshal_object
    result[k] = marshal_schema_object(swagger_spec, prop_spec, v)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/marshal.py", line 50, in marshal_schema_object
    return marshal_object(swagger_spec, schema_object_spec, value)
  File "/Users/zroadhouse/projects/bravado-core/bravado_core/marshal.py", line 124, in marshal_object
    type(object_value), object_value))
bravado_core.exception.SwaggerMappingError: Expected dict like type for <type 'NoneType'>:None
~~~
