### ISSUE TITLE
x-scope tripping up validation?

### ISSUE THREAD

**Issue by mahmoud** [Yelp/bravado-core#119]
Hey all, ran into an issue when loading up a spec. 

First of all, I'm doing 

```python
spec = Spec.from_dict(openapi_spec_dict)
spec.build()
```

Which I hope is the right approach. The spec I'm loading is reproduced below in yaml (with some extraneous parts clipped). I get an error (at the very bottom), which seems to suggest to me that `x-scope` is causing references to not validate? 

Seems far-fetched, I know; I saw all the comments about customizing the validator for exactly this sort of extension. But I'm not sure how to interpret the following error. Any help would be much appreciated!

```yaml
swagger: '2.0'
host: localhost
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
info:
  contact:
    name: ''
  description: ''
  title: ''
  version: '0.1'
paths:
  /admin/campaign:
    post:
      description: Get admin-level details for a campaign, identified by campaign
        ID.
      operationId: get_admin_campaign
      parameters:
      - description: JSON request message for get_admin_campaign
        in: body
        name: get_admin_campaign_request_message
        required: true
        schema:
          $ref: '#/definitions/GetAdminCampaignRequestModel'
      produces:
      - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/GetAdminCampaignResponseWrapper'
definitions:
  GetAdminCampaignResponseWrapper:
    data:
      schema:
        $ref: '#/definitions/CampaignDetails'
      type: object
    errors:
      items:
        type: string
      type: array
    status:
      type: string
    user:
      schema:
        $ref: null
      type: object
```
```
Traceback (most recent call last):
  File "montage/openapi_endpoints.py", line 440, in <module>
    spec = Spec.from_dict(sb.get_openapi_spec_dict())
  File "/home/mahmoud/virtualenvs/montage/local/lib/python2.7/site-packages/bravado_core/spec.py", line 152, in from_dict
    spec.build()
  File "/home/mahmoud/virtualenvs/montage/local/lib/python2.7/site-packages/bravado_core/spec.py", line 159, in build
    http_handlers=build_http_handlers(self.http_client))
  File "/home/mahmoud/virtualenvs/montage/local/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 82, in validate_spec
    http_handlers=http_handlers)
  File "/home/mahmoud/virtualenvs/montage/local/lib/python2.7/site-packages/swagger_spec_validator/common.py", line 22, in wrapper
    sys.exc_info()[2])
  File "/home/mahmoud/virtualenvs/montage/local/lib/python2.7/site-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/home/mahmoud/virtualenvs/montage/local/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/home/mahmoud/virtualenvs/montage/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/home/mahmoud/virtualenvs/montage/local/lib/python2.7/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: {'schema': {'x-scope': [''], '$ref': '#/definitions/GetAdminCampaignResponseWrapper'}} is not valid under any of the given schemas

Failed validating u'oneOf' in schema[u'properties'][u'paths'][u'patternProperties'][u'^/'][u'properties'][u'post'][u'properties'][u'responses'][u'patternProperties'][u'^([0-9]{3})$|^(default)$']:
    {u'oneOf': [{u'$ref': u'#/definitions/response'},
                {u'$ref': u'#/definitions/jsonReference'}]}

On instance[u'paths']['/admin/campaign'][u'post'][u'responses']['200']:
    {'schema': {'$ref': '#/definitions/GetAdminCampaignResponseWrapper',
                'x-scope': ['']}}

```

**Comment by macisamuele** [comment]
Hello @mahmoud  ... I have a look to the specs and seems that the specs are not correct.
I have checked them with [swagger editor](http://editor.swagger.io).

Try to check with this:
```yaml
swagger: '2.0'
host: localhost
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
info:
  contact:
    name: ''
  description: ''
  title: ''
  version: '0.1'
paths:
  /admin/campaign:
    post:
      description: Get admin-level details for a campaign, identified by campaign
        ID.
      operationId: get_admin_campaign
      parameters:
      - description: JSON request message for get_admin_campaign
        in: body
        name: get_admin_campaign_request_message
        required: true
        schema:
          $ref: '#/definitions/GetAdminCampaignRequestModel'
      produces:
      - application/json
      responses:
        '200':
          description: A response description
          schema:
            $ref: '#/definitions/GetAdminCampaignResponseWrapper'
definitions:
  CampaignDetails:
    type: string
  GetAdminCampaignRequestModel:
    type: string
  GetAdminCampaignResponseWrapper:
    properties:
      data:
        $ref: '#/definitions/CampaignDetails'
      errors:
        items:
          type: string
        type: array
      status:
        type: string
      user:
        type: string
```

**NOTE:**
 * ``description`` on the [response object](http://swagger.io/specification/#responseObject) is mandatory
 * [schema object](http://swagger.io/specification/#schemaObject) (ie. ``GetAdminCampaignResponseWrapper``) has the properties defined in the ``properties`` field
 * ``null`` cannot be used as reference since the target cannot be identified and validated

**Comment by mahmoud** [comment]
Thanks, @macisamuele, yes, I had some errors in my pasted version which weren't in the version I was testing, I'm afraid. Unfortunately I've had to reprioritize a bit and I've put a pin in openapi integration.  I still feel like we'll need something in this vein, so I will come back to this. Thank you for all your help!

PS The Swagger Editor is cool, but very frustrating! The error markers in the margin never seem to clear; they just pile up until I refresh. But that's an issue for a different repo :)
