### ISSUE TITLE
UnicodeEncodeError on accentuated characters

### ISSUE THREAD

**Issue by DanielJomphe** [Yelp/bravado-core#25]
Hi, I observed this issue about accentuated characters (like `è`) in the following situations:

1. Descriptions that are going to become docstrings.
2. Response bodies.
3. Request parameters and bodies (potentially; I'm yet to try this one.)

That's with 1.0.0-rc2, downloaded 3 days ago, on 2015-06-08.

Here's an example of situation 1:

```py
api = SwaggerClient.from_url("https://gist.githubusercontent.com/DanielJomphe/b85054e7fb8d2c3ee82e/raw/05472bd55b44531d0e3b68a940da00fc6f886d19/swagger_minimal_accents_case.json")

>>> api.operation.get_operation()
Traceback (most recent call last):
  ...
    api.operation.get_operation()
  File "[…]/bravado_core/resource.py", line 94, in __getattr__
    return operation_docstring_wrapper(op)
  File "[…]/bravado_core/docstring.py", line 53, in operation_docstring_wrapper
    wrapper.__doc__ = create_operation_docstring(operation)
  File "[…]/bravado_core/docstring.py", line 94, in create_operation_docstring
    s += "{0}\n\n".format(desc)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 24: ordinal not in range(128)
```

Here's the [minimal situation 1's swagger.json](https://gist.githubusercontent.com/DanielJomphe/b85054e7fb8d2c3ee82e/raw/05472bd55b44531d0e3b68a940da00fc6f886d19/swagger_minimal_accents_case.json) required to reproduce situation 1:

```json
{
  "swagger": "2.0",
  "info": {
    "title": "Minimal case",
    "version": "1"
  },
  "paths": {
    "/operation": {
      "get": {
        "description": "Minimal case with caractères accentués",
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  }
}
```

I can come back with more details and/or help if you want.

Thanks for sharing this library!

**Comment by analogue** [comment]
@DanielJomphe Thanks for reporting the issue :-) 

I'll work on getting a fix for this in before the 1.0.0 release.

**Comment by analogue** [comment]
FYI, unicode in response bodies worked just fine for me. Wasn't able to reproduce the error.

**Comment by analogue** [comment]
Right, so #29 fixes unicode path params in the request.  Request query params and form params also  verified to be working already.

**Comment by DanielJomphe** [comment]
I upgraded to Bravado 1.0.0 and Bravado-core 1.1.0.

I'm sorry to report there are still issues with Model docstrings, which I didn't remark earlier.

```py
bravado_core/model.pyc in create_model_docstring(model_spec)
230
231         if attr_spec.get('description'):
--> 232             s += " - {0}".format(attr_spec['description'])
233
234         s += '\n\t'

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 19: ordinal not in range(128)
```

Also, the errors in Responses are still there:

```py
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-50-506adf2a1fc6> in <module>()
----> 1 domaines = api.domaines.get_domaines(token="whatever").result()

[…]/bravado/http_future.pyc in result(self, timeout)
30         """
     31         http_response = self.response_adapter(
---> 32             self.future.result(timeout=timeout))
     33 
     34         if self.response_callback:

[…]/bravado/requests_client.pyc in result(self, timeout)
    197             timeout=timeout)
    198 
--> 199         self.check_for_exceptions(response)
    200 
    201         return response

[…]/bravado/requests_client.pyc in check_for_exceptions(self, response)
    182             response.raise_for_status()
    183         except Exception as e:
--> 184             add_response_detail_to_errors(e)
    185 
    186     def result(self, timeout):

[…]/bravado/requests_client.pyc in check_for_exceptions(self, response)
    180     def check_for_exceptions(self, response):
    181         try:
--> 182             response.raise_for_status()
    183         except Exception as e:
    184             add_response_detail_to_errors(e)

[…]/requests/requests/models.pyc in raise_for_status(self)
    832 
    833         if http_error_msg:
--> 834             raise HTTPError(http_error_msg, response=self)
    835 
    836     def close(self):

<type 'str'>: (<type 'exceptions.UnicodeEncodeError'>, UnicodeEncodeError('ascii', u'401 Client Error: Unauthorized : {\r\n  "erreur": {\r\n    "type": "Unauthorized",\r\n    "message": "La valeur du jeton est incompr\xe9hensible."\r\n  }\r\n}', 126, 127, 'ordinal not in range(128)'))
```

**Comment by analogue** [comment]
Can you attach your Swagger schema for the "errors in Response"?

**Comment by DanielJomphe** [comment]
I extracted only the relevant parts, hoping it's all that's required:

[Raw Gist](https://gist.githubusercontent.com/DanielJomphe/a31703ed99f9d631fdde/raw/44c73e52a5bac6ae89fc4c243d102ec281639cf4/swagger_get_domaines_401)

```json
{
  "swagger": "2.0",
  "info": {
    "description": "Some API",
    "version": "1.0.0",
    "title": "SomeApi"
  },
  "host": "somehost.com",
  "basePath": "/api",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/domaines": {
      "get": {
        "description": "Description accentuée.",
        "parameters": [
        ],
        "responses": {
          "200": {
            "description": "Succès."
          },
          "401": {"$ref": "#/responses/401"}
        }
      }
    }
  },
  "definitions": {
    "ErreurProps": {
      "required": [
        "message",
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "example": "sample type",
          "description": "Type de l'erreur. Peut correspondre au status code HTTP"
        },
        "message": {
          "type": "string",
          "example": "sample message",
          "description": "Texte du message comprehensif pour l'utilisateur"
        }
      }
    },
    "Erreur": {
      "required": [
        "erreur"
      ],
      "properties": {
        "erreur": {
          "description": "Definition de l'erreur",
          "$ref": "#/definitions/ErreurProps"
        }
      },
      "description": "Description d'une erreur survenue durant le traitement d'une requete"
    }
  },
  "responses": {
    "401": {
      "description": "Identification invalide.",
      "schema": {
        "$ref": "#/definitions/Erreur"
      },
      "examples": {
        "application/json": {
          "HTTPError: 401 Client Error: Unauthorized :": {
            "erreur": {
              "type": "Unauthorized",
              "message": "Les informations d'authentification ne sont pas reconnues."
            }
          }
        }
      }
    }
  }
}
```
